### ISSUE TITLE
Main article page (api call to get the newest articles from wordpress)

### ISSUE THREAD

**Issue by adamanikiej** [bemin-shaker/theStuteApp#6]

**Comment by adamanikiej** [comment]
pull in the featured articles and then the newest articles

**Comment by adamanikiej** [comment]
see if there is a way to include the ads from the website between articles every like 4 or 5 articles

**Comment by cengelbart39** [comment]
The most recent commits on `main-article` set up Tab and View navigation, with some major reworks to the views and content fetching. This lays the groundwork to work on #7 and add more tabs (such as #8).

Currently, "Top Stories" displays (up to) the 10 most recent featured articles.

I still haven't found a viable way of fetching ads from the API, though.

This is what we're looking at so far:

<img width="300" alt="Screenshot 2023-02-21 at 7 40 28 PM" src="https://user-images.githubusercontent.com/67113079/220491101-f941d9bd-3744-4fde-9894-56859a7bbd36.png"><img width="300" alt="Screenshot 2023-02-21 at 7 40 37 PM" src="https://user-images.githubusercontent.com/67113079/220491120-9e6c5dbf-3e44-4d6a-b4c5-aa1ca3a3ab3c.png">
